# Temperature box register address
RUN_SWITCH_ADRESS = 30
TEMPERATURE_MEASUREMENT_ADRESS = 0
HUMIDITY_MEASUREMENT_ADRESS = 10
TEMPERATURE_SET_VALUE_CURRENT_ADRESS = 2
HUMIDITY_SETVALUE_CURRENT_ADRESS = 12
TEMPERATURE_SET_VALUE_FINAL_ADRESS = 1
HUMIDITY_SET_VALUEF_INAL_ADRESS = 11
TEMPERATURE_SLOPE_ADRESS = 51
# HUMIDITY_SLOPE_ADRESS = 33

# Temperature box control 
SWITCH_ON = 1
SWITCH_OFF = 0

# Temperature limit
HIGH_TEMPERATURE = 90
LOW_TEMPERATURE = -50
HIGHT_SLOPE = 10
LOW_SLOPE = 0